<!doctype html>
<html lang=en >
<head>
<meta charset=utf-8 >
<title>Kallax Wall Bracket Basic R6</title>
<meta name=viewport content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui' >
</head>
<body>
<script src=http://rawgit.com/mrdoob/three.js/dev/build/three.min.js ></script>
<script src=http://rawgit.com/mrdoob/three.js/dev/examples/js/controls/OrbitControls.js ></script>
<script src=http://rawgit.com/mrdoob/three.js/dev/examples/js/libs/stats.min.js ></script>
<script src=http://mrdoob.github.com/three.js/examples/js/libs/tween.min.js ></script>
<script src=http://rawgit.com/mrdoob/three.js/dev/examples/js/libs/tween.min.js ></script>
<script src=../js/mm-r1.js ></script>
<script>

	var components;
	var screws;
	var holes;

	var bracketAssembly;
	var edges;
	var helpers;

	var bracket;
	var part103693; // bracket screw mask
	var screw100372;

	var radiusScrew = 1.5;
	var thickness = 1;

	var v = function( x, y, z ){ return new THREE.Vector3( x, y, z ); };
	var v2 = function( x, y ){ return new THREE.Vector2( x, y ); };

	var pi = Math.PI;
	var pi05 = 0.5 * pi;
	var pi_05 = -0.5 * pi;
	var pi2 = 2 * pi;

	var ran = function( n ) { return n * Math.random(); };
	var cos = function( a ){ return Math.cos( a ); };
	var sin = function( a ){ return Math.sin( a ); };

	var css, menu, stats, renderer, scene, camera, controls;
	var geometry, material, mesh;

	init();
	animate();

	function init() {

		css = document.head.appendChild( document.createElement( 'style' ) );
		css.innerHTML =
		`

			body { font: 12pt monospace; margin: 0; overflow: hidden; }
			button { background-color: #ddd; border: 2px #eee solid; color: #888; }
			h2 { margin: 0 }
			#aa {text-decoration: none; }
			#menu { margin: 0 20px; position: absolute; }

		`;

		menu = document.body.appendChild( document.createElement( 'div' ) );
		menu.id = 'menu';
		menu.innerHTML = 
		`

			<h2>
				<a href="" > ${ document.title } </a>
				<a id=aa href=http://jaanga.github.io/demo/mm/ >🛈</a>
			</h2>
 			<p><button onclick=returnAllToStartTween(); >Return all to start</button>
			<p><button onclick=assembleQuicklyTween(); >Assemble Quickly</button></p>
			<p><button onclick=togglePositions(); >Toggle Positions</button></p>
			<p><input type=checkbox id=chkPlay onchange=togglePlay(); > Play Step-by-Step Assembly</p>
			<div id=info ></div>

		`;

		stats = new Stats();
		stats.domElement.style.cssText = 'position: absolute; right: 0; top: 0; z-index: 100; ';
		document.body.appendChild( stats.domElement );

		renderer = new THREE.WebGLRenderer( { alpha: 1, antialias: true, clearColor: 0xffffff }  );
		renderer.setSize( window.innerWidth, window.innerHeight );
		document.body.appendChild( renderer.domElement );

		camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 1000 );
		camera.position.set( -100, 100, -100 );

		controls = new THREE.OrbitControls( camera, renderer.domElement );
		controls.maxDistance = 800;
		controls.dampingFactor = 0.25;
		controls.enableDamping = true;
		controls.update();

		scene = new THREE.Scene();

		window.addEventListener( 'resize', onWindowResize, false );

		renderer.domElement.addEventListener( 'mousedown', onDocumentMouseDown, false );
		renderer.domElement.addEventListener( 'touchstart', onDocumentTouchStart, false );


// fixtures

		geometry = new THREE.BoxGeometry( 100, 2, 100 );
		material = new THREE.MeshNormalMaterial( { opacity: 0.75, transparent: true });
		mesh = new THREE.Mesh( geometry, material );
		mesh.position.set( 0, -1, 0 );
		scene.add( mesh );

		fixture = drawFixture();
		fixture.position.set( 80, 0, 20 );
		fixture.rotation.set( 0, pi05, 0 );
		scene.add( fixture );

// assets

		drawWallBracketAssembly();


	}

	function drawWallBracketAssembly() {

		scene.remove( bracketAssembly, edges, helpers );

		bracketAssembly = new THREE.Object3D();
		bracketAssembly.name = 'bracketAssembly';

		edges = new THREE.Object3D();
		edges.name = 'edges';

//		helpers = new THREE.Object3D();

		components = [];
		holes = [];
		screws = [];


		bracket = buildKallaxWallBracket();
		bracket.userData.places.push( [ v( 40 - ran( 10 ), 0, -20 ), v( -pi05, 0, ran( 3 ) ) ] );
		bracket.userData.places.push( [ v( 78, 0, -80 ), v( 0, 0, 0 ) ] );
		bracketAssembly.add( bracket );

// 		.userData.places.push( [ v( 0, 0, 0 ), v( 0, 0, 0 ) ] );

		part103693 = drawPart103693();
		part103693.userData.places.push( [ v( 40, 0, 40 - ran( 10 ) ), v( -pi05, 0, ran( 3 ) ) ] );
		part103693.userData.places.push( [ v( 59, 7, -78 ), v( 0, 0, 0 ) ] );
		bracketAssembly.add( part103693 );


		for ( var i = 0; i < 2; i++ ) {

			var mesh = drawScrew100372();
			mesh.position.set( - 15 - ran( 30 ), radiusScrew, ran( 80 ) - 40 );
			mesh.rotation.set( ran( 0.2 ), ran( 6 ), 0 );

			mesh.userData.places = [];
			mesh.userData.places.push( [ v( - 15 - ran( 30 ), radiusScrew, ran( 80 ) - 40  ), v( ran( 0.2 ), ran( 6 ), 0 ) ] );
			mesh.userData.places.push( [ v( 92, 6 + i * 18, -73 ), v( 0, -pi05, 0 ) ] );

			components.push( mesh );
//			screws.push( mesh );
			bracketAssembly.add( mesh );

		}

		scene.add( bracketAssembly );

		drawHelpers2( 50 );

		camera.userData.places = [];
		camera.userData.places.push( [ camera.position.clone(), controls.target.clone() ] );
		camera.userData.places.push( [ v( -100, 100, 100 ), v( 0, 0, 0 ) ] ); // 1. home
		camera.userData.places.push( [ v( 30, 100, -50 ), v( 80, 16, -73 ) ] ); // 2 assembled

		returnAllToStartTween();

		createScreenPlay();

	}


	function createScreenPlay() {

		playList = [

			[ [ bracket, 1, 2000 ] ],
			[ [ part103693, 1, 2000 ] ],
			[ [ components[ 2 ], 1, 2000 ] ],
			[ [ components[ 3 ], 1, 2000 ], [ camera, 2, 1000 ] ]

		];

	}

	function drawFixture() {

			var width = 100;
			var height = 500;
			var thickness = 10;

			var pts = [

				v2( width, height ),
				v2( width, -height ),
				v2( -width, -height ),
				v2( -width, height ),

			];

			var shape = new THREE.Shape();
			shape.fromPoints( pts );

			var holePath = new THREE.Path();
			holePath.absarc( + width - 5 * radiusScrew, 6, radiusScrew, 0, Math.PI * 2, true );
			shape.holes.push( holePath );

			holePath = new THREE.Path();
			holePath.absarc( + width - 5 * radiusScrew, 6 + 18, radiusScrew, 0, Math.PI * 2, true );
			shape.holes.push( holePath );

			geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
			mesh = new THREE.Mesh( geometry, material );

			return mesh;

	}


// http://mrdoob.github.io/three.js/docs/#Reference/Extras.Core/Path
// http://threejs.org/docs/#Reference/Extras.Core/Shape

	function buildKallaxWallBracket() {

		var height = 30;
		var widthLeaf1 = 18;
		var widthLeaf2 = 12;
		var widthCorner = 4;

		var radiusLeaf1 = 4;
		var radiusScrew = 2;
		var segments = 6;

		scene.remove( bracket );

		bracket = new THREE.Object3D();
		bracket.name = 'bracket';
		bracket.castShadow = bracket.receiveShadow = true;

		bracket.userData.places = [];
//		components.push( bracket );
		bracketAssembly.add( bracket );


		material = new THREE.MeshNormalMaterial();

		mesh = buildKallaxWallBracketSide1();
		mesh.position.set( - 0.5 * widthCorner - 0.5 * widthLeaf1, 0.5 * height, 0 );
		bracket.add( mesh );

		buildKallaxWallBracketSide1Lines();
		line.position.set( - 0.5 * widthCorner - 0.5 * widthLeaf1, 0 * height, thickness + 0.01 );
		bracket.add( line );

		mesh = buildKallaxWallBracketSide2();
		mesh.position.set( 0.5 * widthCorner - thickness, 0.5 * height, widthCorner + 0.5 * widthLeaf2 );
		mesh.rotation.set( 0, pi05, 0 );
		bracket.add( mesh );

		buildKallaxWallBracketCorner( 4 );
		mesh.position.set( - 0.5 * widthCorner, height - 4, 0.5 * widthCorner );
		mesh.rotation.set( -pi05, 0, -pi05);
		bracket.add( mesh );

		buildKallaxWallBracketCorner( 4 );
		mesh.position.set( - 0.5 * widthCorner, 0, 0.5 * widthCorner );
		mesh.rotation.set( -pi05, 0, -pi05);
		bracket.add( mesh );

		buildKallaxWallBracketCorner( height - 12 );
		mesh.position.set( 0, height - 6, 0 );
		mesh.rotation.set( pi05, 0, 0 );
		bracket.add( mesh );

		obj = buildKallaxWallBracketSide2Taper()

		obj.position.set( 0.5 * widthCorner - thickness, 0.5 * height, widthCorner + 0.5 * widthLeaf2 );
		obj.rotation.set( 0, pi05, 0 );
		bracket.add( obj );

		components.push( bracket );
		return bracket;

		function buildKallaxWallBracketSide1() {

			var width = widthLeaf1;
			var width05 = 0.5 * width;

			height05 = 0.5 * height;

			pts = [

				v2( width05, height05 ),
				v2( width05, -height05 ),
				v2( -width05, -height05 ),
				v2( -width05, height05 ),

			];

			var holePath = new THREE.Path();
			holePath.absarc( 0, 0, radiusLeaf1, 0, Math.PI * 2, true );

			shape = new THREE.Shape();
			shape.fromPoints( pts );
			shape.holes.push( holePath );

			geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
			mesh = new THREE.Mesh( geometry, material );

			return mesh;

		}

		function buildKallaxWallBracketSide1Lines() {

			var number = 9;
			var diff = 1;

			var width = widthLeaf1;
			var width05 = 0.5 * width;

			var height05 = 0.5 * height;

			var geometry = new THREE.Geometry();

			for ( var i = 0; i < number ; i++ ) {

				geometry.vertices.push( v( -width05 + diff, height - diff - i * diff, 0 ) );
				geometry.vertices.push( v( width05 - diff, height - diff - i * diff, 0 ) );

				geometry.vertices.push( v( -width05 + diff, diff + i * diff, 0 ) );
				geometry.vertices.push( v( width05 - diff, diff + i * diff, 0 ) );

			}

			var material = new THREE.LineBasicMaterial( { color: 0x000000 } );
			line = new THREE.LineSegments( geometry, material  );

			return line;

		}

		function buildKallaxWallBracketCorner( amount) {

			width = widthCorner;
			width05 = 0.5 * width;

			pts = [ v2( -width05, 0 ) ];

			for ( var i = 0; i < segments + 1; i++ ) {

				angle = -pi05 + i * pi05 / segments;
				pts.push( v2( width05 - thickness + thickness * cos( angle), thickness + thickness * sin( angle ) ) );

			}

			pts = pts.concat( [
				v2( width05, width),
				v2( width05 - thickness, width ),
				v2( width05 - thickness, thickness + thickness / segments),
				v2( width05 - thickness - thickness / segments, thickness),
				v2( -width05, thickness),
			] );

			shape = new THREE.Shape();
			shape.fromPoints( pts );
			geometry = shape.extrude( { amount: amount, bevelEnabled: false} );

			mesh = new THREE.Mesh( geometry, material );

			return mesh;

		}

		function buildKallaxWallBracketSide2() {

			var width = widthLeaf2;
			var width05 = 0.5 * width;

			var height05 = 0.5 * height;

			pts = [

				v2( width05, height05 ),
				v2( width05, -height05 ),
				v2( -width05, -height05 ),
				v2( -width05, height05 ),

			];

			shape = new THREE.Shape();
			shape.fromPoints( pts );

			for ( var i = 0; i < 2; i++ ) {

				var x = i === 0 ? width05 - 1.75 * radiusScrew : -width05 + 1.75 * radiusScrew;
				for ( var j = 0; j < 2; j++ ) {

					y = j === 0 ? height05 - 3 * radiusScrew : -height05 + 3 * radiusScrew;

					var holePath = new THREE.Path();
					holePath.absarc( x, y, radiusScrew, 0, Math.PI * 2, true );
					shape.holes.push( holePath );

				}
			}

			geometry = shape.extrude( { amount: thickness, bevelEnabled: false} );
			mesh = new THREE.Mesh( geometry, material );

			return mesh;

		}

		function buildKallaxWallBracketSide2Taper() {

			var obj = new THREE.Object3D();

			for ( var i = 0; i < 2; i++ ) {

				var x = i === 0 ? width05 - 2.25 * radiusScrew : -width05 + 2.25 * radiusScrew;

				for ( var j = 0; j < 2; j++ ) {

					y = j === 0 ? height05 - 3 * radiusScrew : -height05 + 3 * radiusScrew;

					pts = [ v( radiusScrew, 0, thickness ) , v( radiusScrew - thickness, 0, thickness ), v( radiusScrew, 0, 0 ) ];

					geometry = new THREE.LatheGeometry( pts, 4 * segments );
					mesh = new THREE.Mesh( geometry, material );
					mesh.position.set( x, y, 0 );

					obj.add( mesh );

				}

			}

			return obj;

		}

	}

	function drawPart103693() {

		var startX;
		var startY;
		var rectWidth;
		var rectWidth05;
		var rectHeight;
		var radius1;
		var radius2;

		scene.remove( part103693 )
		part103693 = new THREE.Object3D();

		material = new THREE.MeshNormalMaterial();

		startX = 0
		startY = 0;
		rectWidth = 15;
		rectWidth05 = 0.5 * rectWidth;
		rectHeight = 20;
		radius1 = 2.25;
		radius2 = 3.5;
		radius3 = 1;

		var pts = [ 
			v2( startX, startY ), 
			v2( startX + rectWidth, startY ),
			v2( startX + rectWidth, startY + rectHeight ),
			v2( startX, startY + rectHeight ),
		];

// main section with keyhole
		var shape = new THREE.Shape();
		shape.fromPoints( pts );

		var holePath = new THREE.Path();

		holePath.absarc( startX + rectWidth05, startY + 5 * radius1, radius1,  0, pi );
		holePath.moveTo( startX + rectWidth05 + radius1, startY + 8.25 );
		holePath.absarc( startX + rectWidth05, startY + radius1 + radius2, radius2, pi - 0.8, pi2 + 0.8 );

		shape.holes.push( holePath );

		var geometry = shape.extrude( { amount: thickness, bevelEnabled: false } );

// bumps
		shape = new THREE.Shape();

		shape.absarc( startX + radius1, startY + rectHeight - 1 * radius1, radius3, 0, pi );
		shape.absarc( startX + radius1, startY + 1 * radius1, radius3, pi, pi2 );
		geo2 = shape.extrude( { amount: thickness, bevelEnabled: false } )
		geo2.applyMatrix( new THREE.Matrix4().makeTranslation( 0, 0, thickness ) );
		geometry.merge( geo2 );

		geo2 = geo2.clone();
		geo2.applyMatrix( new THREE.Matrix4().makeTranslation( rectWidth - 2 * radius1, 0, 0 ) );
		geometry.merge( geo2 );

// curved ends
		shape = new THREE.Shape();
		shape.absarc( startX + 2 * thickness, 0, thickness + 2, pi, 1.25 * pi );
		shape.moveTo( startX, 0 );
		shape.absarc( startX + 2 * thickness, 0, 2, 1.25 * pi, pi );

		geo2 = shape.extrude( { amount: rectWidth, bevelEnabled: false } );
		geo2.applyMatrix( new THREE.Matrix4().makeRotationY( pi05) );
		geometry.merge( geo2 );

		geo2 = geo2.clone();
		geo2.applyMatrix( new THREE.Matrix4().makeRotationZ( pi ) );
		geo2.applyMatrix( new THREE.Matrix4().makeTranslation( rectWidth, rectHeight, 0 ) );

		geometry.merge( geo2 );
		geometry.mergeVertices ();

		mesh = new THREE.Mesh( geometry, material );
		mesh.name = 'part103693';
		mesh.userData.places = [];
		components.push( mesh );

		return mesh;

	}

	function drawScrew100372() {

//		scene.remove( screw100372 );

		var screw = new THREE.Object3D();

//		var radiusScrew = 4;
		var radiusScrew05 = 0.5 * radiusScrew;

		var delta = 2;

		var height = 20;
		var height05 = 0.5 * height;

		var pitch = 2;
		var segments = 18;

		material = new THREE.MeshNormalMaterial( { side: 2 } );
		points = [ 

			v( 0, 0, height05 + 2) , 
			v( delta, 0, height05 + 2 ), 
			v( delta, 0, height05 + delta + 1), 
			v( radiusScrew05 + delta, 0, height05 + delta + 1 ), 
			v( radiusScrew05, 0, height05 ),

			v( radiusScrew05, 0, -height05 ),
			v( 0, 0, -height05 - delta ) 

		];

		geometry = new THREE.LatheGeometry( points, segments );

		mesh = new THREE.Mesh( geometry, material );
		screw.add( mesh );

		mesh = drawSpiralAlongZ( radiusScrew05, radiusScrew05 + 1, segments, height / pitch, pitch );
//		mesh.scale.set( -1, -1, -1 );
		screw.add( mesh );

		function drawSpiralAlongZ( rIn, rOut, seg, tur, pit ) {

			var radiusInside = rIn ? rIn : 10;
			var radiusOutside = rOut ? rOut : 15;

			var segments = seg ? seg : 36;
			var turns = tur ? tur : 7;
			var segementsTotal = turns * segments;

			var pitch = pit ? pit : 15;
			var pitchDelta = pitch / segments;

			var angleDelta = pi2 / segments;

			var geometry = new THREE.PlaneBufferGeometry( 1, 1, 1, segementsTotal );

			var arr = geometry.attributes.position.array;

			for ( var i = 0; i < arr.length; ) {

				if ( arr[ i ] < 0 ) {

					var delta = i / 6;
					arr[ i++ ] = radiusInside * cos( angleDelta * delta );
					arr[ i++ ] = radiusInside * sin( angleDelta * delta );
					arr[ i++ ] = pitchDelta * delta;

					arr[ i++ ] = radiusOutside * cos( angleDelta * delta );
					arr[ i++ ] = radiusOutside * sin( angleDelta * delta );
					arr[ i++ ] = pitchDelta * delta;

				}

			}

			geometry.computeFaceNormals();
			geometry.computeVertexNormals();
			geometry.center();

			var material = new THREE.MeshNormalMaterial( { side: 2 } );
			var mesh = new THREE.Mesh( geometry, material );

			return mesh

		}

		screw.name = 'screw100372';

		return screw;

	}


	function onWindowResize() {

		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();

		renderer.setSize( window.innerWidth, window.innerHeight );

	}

	function animate() {

		requestAnimationFrame( animate );
		controls.update();
		stats.update();
		TWEEN.update();
		renderer.render( scene, camera );

	}

</script>
</body>
</html>